#!/usr/bin/env python3
"""
Writing strings to Redis
"""
from typing import Callable, Union
import functools
import redis
import uuid


def count_calls(method: Callable) -> Callable:
    """
    Function that count how many
    times methods of the Cache class are called
    """
    key = method.__qualname__

    @functools.wraps(method)
    def wrapper(self, *args, **kwargs):
        """wrapper method."""
        self._redis.incr(key)
        return method(self, *args, **kwargs)
    return wrapper


def call_history(method):
    """
    Function add its input parameters to one list
    in redis, and store its output into another list.
    """
    input_key = method.__qualname__ + ":inputs"
    output_key = method.__qualname__ + ":outputs"

    @functools.wraps(method)
    def wrapper(self, *args, **kwargs):
        """Wrapper method"""
        self._redis.rpush(input_key, str(args))
        output = method(self, *args, **kwargs)
        self._redis.rpush(output_key, str(output))

    return wrapper


class Cache:
    """
    Writing strings to Redis
    """

    def __init__(self) -> None:
        """
        Construct redis database
        """
        self._redis = redis.Redis()
        self._redis.flushdb()

    @count_calls
    def store(self, data: any) -> str:
        """
        Method used to store data in
        Redis with a randomly generated key
        """
        Randk = str(uuid.uuid4())
        self._redis.set(Randk, data)
        return Randk

    def get(self, key: str, fn: Callable = None) -> Union[
                                                        str, bytes, int,
                                                        float]:
        """
        get method retrieves data from Redis using the specified key.
        It accepts an optional conversion function (fn) to convert the
        retrieved data back to the desired format.
        """

        data = self._redis.get(key)
        if data is None:
            return None
        if fn is not None:
            return fn(data)
        return data

    def get_str(self, key: str) -> str:
        """
        Method which will automatically parameterize
        to string.
        """
        return self.get(key, fn=lambda d: d.decode("utf-8"))

    def get_int(self, key: str) -> int:
        """
        Method which will automatically parameterize
        to integer.
        """
        return self.get(key, fn=int)
